name: CI
on: [push, pull_request]

jobs:
  build-and-test:
    name: Cargo run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo test
